로또테스트입니다.
code-squad/masteringjs_lotto pull request #1
Opened 2018-09-01 09:18 UTC by jeonghoyoo

테스트로 풀리퀘 해봅니다.

2018-09-02 03:10 UTC, crongro requested changes
네 이제 본격 개발하시면 됩니다 ^^

2018-09-03 00:23 UTC, crongro requested changes
후다닥 잘 하셨네요~ 
리뷰 남깁니다. 수정해보세요~

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +    function buyLottos(payAmount){
현재는 전역공간에 함수를 둘수밖에 없는데요.
buyLottos 함수 안에 내부함수를 두지 않고, 밖으로 빼도 될 거 같습니다. 
나중에 객체나 클래스 형태로 코드를 구현하면  자연스럽게 해결될거고요. 지금은 오히려  buyLottos 함수의 몸짓만 너무 커져서 좋지 않아보입니다.

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +        function printLottoGroup(singleLotto){
print라는 이름으로 지어져있지만 문자열을 반환하는 함수네요. 이름과 결과값이 일치하도록 하시면 좋겠습니다.

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +                if(index === 0)
한줄짜리 if/else라면 (더구나 brace없이구현한다면) 개행을하지 않는게 좀더 나을거 같아요.

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +            for(let i=0 ; i < 6; i++){
별건 아니지만 6이 뜻하는 의미가 무엇인지 생각해볼필요가 있죠. 
magic number라고 하는 이런 의미를 알기 어려운 숫자를 없애도록 해보세요.

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +        for(let i=0 ; i < payAmount / 1000 ; i++){
6과 마찬가지로 1000이라는 숫자가 어떤 의미인지 좀더 알려면 어떻게 해야할까요?

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +            return value.filter(innerValue => {
filter를 잘 사용하셨네요.

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +                var innerFlag = checkWhetherExistOrNot(innerValue);
const를 기본으로 사용해보시고 문제가 생기면 let을 사용하는 걸 해보세요~

2018-09-03 00:23 UTC, crongro commented on lotto.html
> +            if(value.length >= 3){
value.length를 반복적으로 계산하는 코드네요.

2018-09-03 12:36 UTC, jeonghoyoo commented
남겨주신 리뷰 내용 모두 수정하여 다시 푸시하였습니다.

2018-09-04 00:01 UTC, crongro approved these changes
잘 하셨어요~ 
참고할겸 리뷰 좀더 남깁니다.

Approve 하고 머지 합니다.
수고하셨어요.

2018-09-04 00:01 UTC, crongro commented on lotto.html
> +    const arrLottsGroupForCustomer = [];
참고로 전역공간에 있는 것을 모두 없애고 모듈화를 하려면 
즉시실행함수로 전체를 감싸면 되긴합니다. 
단지 외부에서 접근하기가 어려운 구조가 됩니다.

2018-09-04 00:01 UTC, crongro commented on lotto.html
> +    const LOTTO_MAX_DIGITS = 6;
이런값이 많아지면 객체로 네이스페이스를 만들어서 관리하면 좋더라고요.

const data = {
  LOTTO_MAX_DIGITS :6,
  MIN_PRIZE_COUNT:3
}

이런식으로요.

2018-09-04 00:01 UTC, crongro commented on lotto.html
> +        singleLotto.forEach((value, index) => {
예습할결 forEach말고 reduce메서드의 사용법도 미리 공부해보세요.

2018-09-04 00:01 UTC, crongro commented on lotto.html
> +        for(let i=0 ; i < LOTTO_MAX_DIGITS ; i++){
for-of로 앞으로 for문을 대체할 수 있을겁니다.
사실 더 좋은건 forEach나 filter,map등의 메서드를 사용하는 것이고요.

2018-09-04 00:01 UTC, nigayo commented on lotto.html
> +        for(let i=0 ; i < payAmount / LOTTO_BUY_PRICE ; i++){
payAmount / LOTTO_BUY_PRICE 이 값이  동일한 결과인가요? 
그렇다면 for문 앞에서 미리 계산해두고 변수에 저장해두고 쓰면 좋겠네요.

2018-09-04 00:01 UTC, merged