로또 프로그램 리뷰 요청드립니다.
code-squad/masteringjs_lotto pull request #11
Opened 2018-09-05 14:27 UTC by hyeyoon

로또 프로그램 리뷰 요청드립니다. :)

2018-09-05 23:18 UTC, crongro requested changes
함수단위로 잘 구현하셨어요.

전역변수는 좀 줄여야할 거 같아요 ^^
리뷰드린 내용 참고해서 조금 수정해보세요.

그리고 commit -> push 만 하시면 됩니다.

2018-09-05 23:18 UTC, nigayo commented on lotto.js
> + *  @param {Number} count - 구매할 로또의 수
이런방법으로 주석에 반환값이나 파라미터를 쓰는 건 좋아요.
typescript를 사용하면 이런장점을 대체하게 됩니다.

2018-09-05 23:18 UTC, nigayo commented on lotto.js
> +  statistics['count'] = array.reduce((prev, curr) => (prev[curr] = ++prev[curr] || 1, prev), {});
reduce 동작방법에 대해서 한번 설명 좀 댓글로 해주세요. 짧게요~

2018-09-05 23:18 UTC, nigayo commented on lotto.js
> +    const filteredNumbers = numbers.filter((number, idx, arr) => (arr.indexOf(number) === idx && number >= minNumber && number <= maxNumber));
콜백함수 코드가 길면 (가로스크롤이 생길정도) { } 와 함께 개행을 하는 것도 좋습니다.

2018-09-05 23:18 UTC, nigayo commented on lotto.js
> +const lottoPrice = 1000;
전역변수가 많네요.
어쩔수없이 전역변수를 사용해야할 수도 있습니다.
다만, 지금 과제에서는 필요 없는 것들도 있습니다.
따라서 몇몇 변수를 함수로 옮기고, 다른 함수로 전달해야 하면 '인자'를 써서 옮기도록 하시고요.
이런식으로 여기 선언된 변수를 대거~ 제거해보세요.

2018-09-05 23:18 UTC, nigayo commented on lotto.js
> +      checkLottos();
전역변수이야기를 드렸는데요.
checkLottos에 lottos값을 인자로 luckyNumbers를 전달해줄수도 있겠네요.

2018-09-06 13:59 UTC, hyeyoon commented on lotto.js
> +  statistics['count'] = array.reduce((prev, curr) => (prev[curr] = ++prev[curr] || 1, prev), {});
-  reduce 함수는 배열의 요소를 순환하며 각 배열의 요소에 실행할 함수를 변수로 받는데, 함수는 accumulator(누산기 → mdn 용어를 참고했습니다.)와 현재 처리되는 값을 받고, option으로 인덱스값과 reduce를 실행하는 배열을 받습니다.

- 작성한 함수의 경우 initialValue로 빈  객체를 받아서 로또 결과값이 담긴 배열을 순회하면서 중복된 요소의 수를 계산하는 콜백함수를 받고 있습니다. 좀 더 직관적으로 함수를 풀어서 작성하면 이렇게 작성할 수 있을 것 같습니다.

2018-09-06 14:01 UTC, hyeyoon commented
리뷰해주신 것을 바탕으로 코드를 수정해봤습니다 :)

2018-09-07 00:17 UTC, nigayo commented on lotto.js
> +  statistics['count'] = array.reduce((prev, curr) => (prev[curr] = ++prev[curr] || 1, prev), {});
@hyeyoon 설명감사해요. 앞으로 잘 활용하시면 좋겠습니다.

2018-09-07 00:22 UTC, crongro approved these changes
아주 잘 구현하셨어요~ 
💯

2018-09-07 00:22 UTC, crongro commented on lotto.js
> +  const lottoPrice = 1000;
이것도 lottoPirce도 data 객체에 둘 수 있어보이네요.

2018-09-07 00:22 UTC, crongro commented on lotto.js
> +const getRandomNumbers = () => {
잘 구현하셨어요. 
복잡한 알고리즘을 하위함수로 계속 이렇게 분리하는 게 좋습니다.

2018-09-07 00:22 UTC, crongro commented on lotto.js
> +  if (Array.isArray(numbers)) {
numbers 라고하니까 숫자들로 해석이 돼서 무엇인지 좀  알기 어렵습니다.
좀더 구체적이면 좋겠네요.

2018-09-07 00:22 UTC, crongro commented on lotto.js
> +  countWin(results);
통계기능을 별도로 잘 위임시켰네요.

2018-09-07 00:22 UTC, merged