로또 프로그램, 객체 실습 1,2 리뷰 요청 드립니다.
code-squad/masteringjs_lotto pull request #4
Opened 2018-09-02 16:41 UTC by khw1031

안녕하세요 크롱님
객체 실습 1,2와 로또 프로그램 코드 리뷰 요청 드립니다.

2018-09-03 01:11 UTC, crongro requested changes
js의 특징을 잘 이해하고 계세요.
특별히 수정할건 없지만 리뷰 남깁니다.
의견드린부분들 참고해서 고민해보세요 ~

2018-09-03 01:11 UTC, crongro commented on LottoGen/index.js
> +  const matchCase = {
matchCase와  price를 하나의 객체로 합칠수도 있겠네요.

2018-09-03 01:11 UTC, crongro commented on LottoGen/index.js
> +  class Lotto {
아 클래스를 이해하고 잘 쓰셨군요. 👍

2018-09-03 01:11 UTC, crongro commented on LottoGen/index.js
> +  return Lotto
일종의 모듈패턴을 사용하셨군요. private요소를 숨길 수 있어서 좋네요.

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +  class Lotto {
다만 이부분이 꼭 class이어야할까? 라는 건  생각해볼필요는 있습니다. 
함수들로만 구현해서 일관된  패턴을 만들수도 있고요.

 class형태로 모듈화를 한다면 오히려 class 로만 코드를 몇개 구성할수도 있고요.

지금은 function/class가 큰 장점을 갖지 않고 섞여 있어서 그건 생각해볼만한 부분이네요.

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +      moneyBought = moneyAmount
class안에서 class밖의 변수에 접근하고 쓰는게 어색해보이네요. 흔하진 않은 일이라서요 .

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +    for (let i = numbers.length - 1; i >= 0; i--) {
앞으로 for문을 for-of나 foreach 등으로 대체해서 구현해보세요~

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +      console.log(`당첨 통계`)
console.log로 출력하는 부분을 별도 함수로 빼보세요~

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +  const checkLottoNumber = lottoNumber => {
이 코드가 반복을 3번 중첩하고 있는데요. 복잡도가 높아보입니다.
알고리즘을 개선해보면 좋겠어요. 한번 고민해주세요 ^^

2018-09-03 01:11 UTC, nigayo commented on LottoGen/index.js
> +    const earningRate = ((earnedMoney - moneyBought) / moneyBought) * 100
100이 뜻하는게 무엇인죠? magic number는 없을수록 더 좋습니다~

2018-09-03 01:11 UTC, nigayo commented on 객체실습/practice02.js
> +  const recursiveFind = data => {
👍

2018-09-03 01:11 UTC, nigayo commented on 객체실습/practice02.js
> +      if (type === 'sk') {
sk문자열도 변경될 수 있다고 가정하면  함수의 인자로 받는것도 좋겠네요.

2018-09-04 11:06 UTC, khw1031 commented
@nigayo 객체실습2번, 로또 프로그램 피드백 반영해서 수정했습니다. 코드가 좀 많이 바뀌어서 전체 보기로 보시는게 좀 더 편하실 것 같습니다 :)

2018-09-04 14:58 UTC, crongro requested changes
대대적인 리팩토링이군요!
prototype  키워드는 말할것도 없이 중요한데요.
곧 배우겠지만 미리 학습하시는 건 더 좋죠~

리뷰참고해서 필요한 부분 약간 더 수정부탁드려요.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +const Utils = {
Utils 네임스페이스로 묶은건 아주 좋은데요.
객체리터럴을 할때는 arrow함수를 잘 안씁니다.
(this가 윈도우를 가리켜요)

간단히 이렇게 구현해보세요.
```
const util = {
   swap(a,b,c) {
   }
}
```

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +    PRIZE_AND_MATCH_NUMBER_COUNT = {
긴 이름이지만 명확해서 좋네요.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +  const _Lotto = function() {}
_로 시작하는 건 보통 private인데요, 오히려 여기서는 반대로 public에 사용하신거 같아요.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +  const checkLottoNumber2 = winningNumber => {
아 이함수는 테스트용? 이군요.
every등 사용이 좀 이상해보였습니다.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +      if (PRIZE_AND_MATCH_NUMBER_COUNT[count] != null) {
방어적인 코드 좋아요.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +        PRIZE_AND_MATCH_NUMBER_COUNT[count].count++
count 와 count이름이 겹치이 약간 어색하네요 ㅎ

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +  const generateNumber = (min = 1, max = 45) => {
default parameter잘 사용했어요.

2018-09-04 14:58 UTC, nigayo commented on LottoGen/index.js
> +      setMoneyBought(money)
buyLotto 는 무엇을 하는지 순차적으로 보여서 보기 좋습니다.
다만 의심스러운건,  반환값을 통해서 다른 함수의 입력으로 넣을 부분도 없을까? 라는 건데요.
아래 함수리스트만 보면 서로 관련이 없는거 같지 않은데, 출력->입력으로 데이터 흐름이 보이면 더 좋겠어요.
아마 이렇게 되면 함수외에 선언된 변수가 좀더 줄 수 있습니다.

2018-09-05 13:49 UTC, khw1031 commented
@nigayo 수정했습니다!

2018-09-05 23:10 UTC, crongro approved these changes
잘 구현했습니다! 
리뷰몇줄은 참고하세요

2018-09-05 23:10 UTC, nigayo commented on LottoGen/index.js
> +  Lotto.prototype = {
3주차에 객체지향을 배우는데요, 
그때 prototype에 대해서 좀 이야기할 시간이 있습니다.

2018-09-05 23:10 UTC, nigayo commented on LottoGen/index.js
> +      const duplicationRemovedArray = new Set([...winningNumber, ...eachCase])
아 다른분도 이방법을 사용하셨던데, 좋은 거 같아요

2018-09-05 23:10 UTC, nigayo commented on LottoGen/index.js
> +  const getPublishedLottos = () => publishedLottos
이 함수는 쓰지 않고 있음으로,  지워도 되겠군요.
getter/setter가 꼭 있어야 하는 건 아니죠.

2018-09-05 23:10 UTC, nigayo commented on LottoGen/index.js
>      console.log(`로또 ${iterableCount}개를 발행했습니다.`)
template literal잘 사용했어요~

2018-09-05 23:10 UTC, merged