로또
code-squad/masteringjs_lotto pull request #8
Opened 2018-09-05 04:33 UTC by igemukko

로또 생성 및 당첨번호 확인 js 입니다. 리뷰 부탁드립니다.

2018-09-05 13:20 UTC, crongro requested changes
잘 하셨어요!!
주석기반으로 코드설명이 습관이 잘 되신거 같네요. 

고민거리를 좀 남겨드리니 참고하셔서 수정해보세요 ^^

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +let luckyNum =[];
전역변수는 없을수록 좋죠. 
luckyNum은 함수안에서 선언하고, 다른함수에서  이 값이 필요하면 인자로 전달해주면 될 거 같아보이네요.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    //에러메시지
코드의 주석이 많아서 보기 좋아요.
그런데 약간 많은 정도입니다. 이런습관을 좀더 줄이시고 코드 자체에서 '의도'를 더 잘 드러내도록 해보시면 좋겠어요.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    const errorMsg = "1000원이상 구매 가능합니다.";
errorMsg 보다는 에러메시지가 여러개 있을 수 있으니, 이름도 구체적으로 쓰고요,
이렇게 하셔도 될 듯.

const ErrorMsg = {
  "BASE_MONEY" :  "1000원은 넣어야지 않겠냐?" 
}

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    generateResult.forEach(function (a){
이런상황에서 화살표함수를 쓰면 좋죠.
함수의 인자로 사용되는 함수나 
함수의 반환값으로 사용될때 편리합니다.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    let rotto = new Object();
new Function, new Array, new String 
다 이렇게 객체를 만들수 있는 방법인데요.
잘 안써요. 특별히 장점이 없어서요.

let lottoObject = {};
이렇게 하시면 될 듯 합니다.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +        tmpRotto = tmpRotto.concat(Math.floor(Math.random()*45)+1);
concat 잘 쓰셨어요. 그런데 배열에  추가할때는 push가 좀더 일반적인거 같아요.
concat는 배열간의 merge때 필요한거 같고요.
이름에서 그 용도가 다 있으니 적절히 써보세요. 잘 모르겠으면 MDN의example을 보는 습관도 도움이 됩니다.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +let generateResult = [];
이 변수의 이름은 약간 별로에요.
generatedLottoList 같은건가요?

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    console.log("1개 일치 (0원)- " + matchResult[0] +"개");
1개일치,2개일치는 제외해도 되겠네요~

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    for(let i of generateResult){
배열을 반복할때 for-of를 표준처럼 쓰면 좋아요. 잘했어요.
iteration protocol이라고 이제 반복문의 표준처럼 사용되고 있어요.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    return rotto;
rotto .. 라는 이름이 절 슬프게 합니다.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +        rotto.num = tmpRotto.filter((item, idx, array) => {
여긴 arrow function을 적절히 잘 쓰셨네요.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    let matchResult = [0,0,0,0,0,0];
변수이름에 '동사'를 쓰지마시고요.
명사위주로 쓰면 더 좋아요~

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +        for(let j of luckyNum){
for-of 를 쓸때 아무의미 없는 i,j 라는 이름대신 제대로된 의미를 변수에 부여해보면 좋겠어요.

2018-09-05 13:20 UTC, crongro commented on lotto.js
> +    for(let i of generateResult){
아 그런데 여기반복문은 index가 필요한거라.. for 문이 더 나을 수도 있겠네요.(tmpIndex라는 걸 쓰고 계시길래)

2018-09-06 01:13 UTC, igemukko commented on lotto.js
> +    return rotto;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 🤔😅🤣

2018-09-06 11:03 UTC, crongro approved these changes
잘 하셨어요.
리뷰참고해서 좀더 개선해보셔도 좋고요.
코드는 여기서 머지할게요~

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +    //구매금액 유효성 체크
개행도 있고 주석도 있어서 당장 코드 읽기가 좋네요 ㅎ
배포할때는 주석을 제거하고 배포하곤하죠. 개행도 물론 없애고요. 
그런데 주석이 많은 코드는 좋지만, 자칫 의도가 잘 드러나지 않는 코드를 주석으로 설명해서 마무리하는 경우가 있을 수 있으니..
그것만 조심하세요~

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +            genLottos = genLottos.concat(RandomGeneratelottoNum());
concat은 배열을 합칠때 더 많이 쓰여요. 
배열에 요소를 추가할때는 push가 좀더 와닿는 거 같네요.

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +    const ErrorMsg = {
👍

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +    else if(price > 100000) console.log(ErrorMsg.MAX_MONEY);
저 같으면 이렇게 했을 거 같아요.

```javascript

function validationMoney(price) {
  const MINVALUE = 1000;

  const ErrorMsg= {
   "MIN_MONEY"  : `${MINVALUE} 원이상 구매 가능합니다`
  }
 if(price < MINVALUE) console.log(ErrorMsg.MIN_MONEY);
}

validationMoney(900);
```

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +function RandomGeneratelottoNum(){
반환값이 lottoObj 인, object타입이네요.
그렇다면 이름도..
randomGenerateLottoObj() 
가 좀더 무엇을 하는지 예상할 수 있어보여요.

그리고 함수이름을 대문자로 시작하면 생성자(constructor)로 취급합니다.
다시말해 new 키워드로 불려지는 것으로 예상합니다.

2018-09-06 11:03 UTC, crongro commented on lotto.js
> +        luckyNumbers.forEach((luckyNum) => {
filter 메서드를 쓸 수도 있어보이네요.

2018-09-06 11:03 UTC, nigayo commented on lotto.js
> +    console.log("1개 일치 (0원)- " + result[0] +"개");
console.log 로 비슷한 내용을 출력하고 있는 여기 중복코드를 좀 개선할 수 없을지 고민해보세요.

2018-09-06 11:03 UTC, merged